### PR TITLE
Upgrade to actions/setup-node@v3

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Review by Qasim1234567890 — APPROVED** [review]

**Review by paul1974nsac — COMMENTED** [review]
Leave submit

**Comment by paul1974nsac** [comment]
Leave comment

**Review by paul1974nsac — APPROVED** [review]

**Review by paul1974nsac — APPROVED** [review]
Leave comment

**Review by paul1974nsac — APPROVED** [review]
Leave comment

**Review by paul1974nsac — APPROVED** [review]
No comment

**Review by paul1974nsac — APPROVED** [review]
#169

**Review by Paasioa — APPROVED** [review]

**Comment by EVGENII96-desing** [comment]
https://github.com/actions/checkout/pull/754/commits/523889fd2f6a4835708a7a8bbefad9e633e00988

Евтехова Е. С.

пт, 8 апр. 2022 г., 08:28 Christian Clauss ***@***.***>:

**Review by ReginaLayna1 — APPROVED** [review]
Nice

**Review by ReginaLayna1 — CHANGES_REQUESTED** [review]
Nice

**Pull request closed without merging**
