### PR TITLE
Add workflow file for publishing releases to immutable action package

### PR DESCRIPTION
**Pull request by Jcambass**
This workflow file publishes new action releases to the immutable action package of the same name as this repo.

This is part of the Immutable Actions project which is not yet fully released to the public. First party actions like this one are part of our initial testing of this feature.

### CODE REVIEW

**Review by joshmgross — APPROVED** [review]

**Review by ratchanonsuttawas — APPROVED** [review]

**Review by ratchanonsuttawas — APPROVED** [review]

**Comment by ratchanonsuttawas** [comment]
> This workflow file publishes new action releases to the immutable action package of the same name as this repo.
> 
> This is part of the Immutable Actions project which is not yet fully released to the public. First party actions like this one are part of our initial testing of this feature.

**Review by ratchanonsuttawas — APPROVED** [review]

**Review by ratchanonsuttawas — APPROVED** [review]

**Review by ratchanonsuttawas — CHANGES_REQUESTED** [review]
+20 -0

**Review by ratchanonsuttawas — APPROVED** [review]

**Review by ratchanonsuttawas — APPROVED** [review]

**Review by Dev-Re2906 — COMMENTED** [review]
publish

**Review by Dev-Re2906 — COMMENTED** [review]
publish

**Pull request merged**
