### PR TITLE
Add in explicit reference to private checkout options

### LINKED ISSUE #1021: checkout-multiple-repos-side-by-side doc example
The [README.md](https://github.com/actions/checkout#readme) contains example for mulitple checkouts in the context of one organization, if I'm not wrong.
May be, it's about to checkout public repository.

There is another example - checkout-multiple-repos-private, but is a repository of the same organization on GitHub for which the GitHub action is run, is considered "private" as well?

I thought if I run the action in private repository for my organization, other private repositories are accessible.
If not, it's better to precise the documentation by adding to "Checkout multiple repos (private)" something like:

...so if your want to checkout a different repository that is private **(no matter if it's the same organization on GitHub or not)**...

and to "Checkout multiple repos (side by side)" example to add something like:

Attention! You second repository must be public, even if it's from the same organization on GitHub that the action repository.

### PR DESCRIPTION
**Pull request by vanZeben**
Updated the README to link to the private repo checkout and be explicit about it.

Fixes #1021

### CODE REVIEW

**Review by johnsudol — APPROVED** [review]
lgtm

**Comment by QQAAZZw12345** [comment]
gh pr checkout 1050

**Review by QQAAZZw12345 — COMMENTED** [review]
README.md

>  @`
3ABF15AA-887C-4396-8144-D3E6D3BC3670
#陳彥良
Duplicate of #`

**Comment by QQAAZZw12345** [comment]
gh pr checkout 1050

**Review by QQAAZZw12345 — COMMENTED** [review]
README.md

**Pull request merged**
